/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgendaPublicaRouteImport } from './routes/_authenticated/agenda-publica'
import { Route as AuthenticatedCompletarCadastroRouteImport } from './routes/_authenticated/completar-cadastro'
import { Route as AuthenticatedOrganizacaoRouteImport } from './routes/_authenticated/organizacao'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedSetorRouteImport } from './routes/_authenticated/setor'
import { Route as AuthenticatedViagensRouteImport } from './routes/_authenticated/viagens'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminCidadesRouteImport } from './routes/_authenticated/admin.cidades'
import { Route as AuthenticatedAdminDestinosRouteImport } from './routes/_authenticated/admin.destinos'
import { Route as AuthenticatedAdminDisponibilidadeRouteImport } from './routes/_authenticated/admin.disponibilidade'
import { Route as AuthenticatedAdminSolicitacoesRouteImport } from './routes/_authenticated/admin.solicitacoes'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedSolicitacoesIndexRouteImport } from './routes/_authenticated/solicitacoes.index'
import { Route as AuthenticatedSolicitacoesNovaRouteImport } from './routes/_authenticated/solicitacoes.nova'
import { Route as AuthenticatedAdminMotoristasIndexRouteImport } from './routes/_authenticated/admin.motoristas.index'
import { Route as AuthenticatedAdminMotoristasDriverIdRouteImport } from './routes/_authenticated/admin.motoristas.$driverId'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './routes/_authenticated/admin.usuarios.index'
import { Route as AuthenticatedAdminUsuariosUserIdRouteImport } from './routes/_authenticated/admin.usuarios.$userId'
import { Route as AuthenticatedAdminVeiculosIndexRouteImport } from './routes/_authenticated/admin.veiculos.index'
import { Route as AuthenticatedAdminVeiculosVehicleIdRouteImport } from './routes/_authenticated/admin.veiculos.$vehicleId'
import { Route as AuthenticatedSolicitacoesTripIdEditarRouteImport } from './routes/_authenticated/solicitacoes.$tripId.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaPublicaRoute =
  AuthenticatedAgendaPublicaRouteImport.update({
    id: '/agenda-publica',
    path: '/agenda-publica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompletarCadastroRoute =
  AuthenticatedCompletarCadastroRouteImport.update({
    id: '/completar-cadastro',
    path: '/completar-cadastro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizacaoRoute =
  AuthenticatedOrganizacaoRouteImport.update({
    id: '/organizacao',
    path: '/organizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetorRoute = AuthenticatedSetorRouteImport.update({
  id: '/setor',
  path: '/setor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViagensRoute = AuthenticatedViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminCidadesRoute =
  AuthenticatedAdminCidadesRouteImport.update({
    id: '/admin/cidades',
    path: '/admin/cidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDestinosRoute =
  AuthenticatedAdminDestinosRouteImport.update({
    id: '/admin/destinos',
    path: '/admin/destinos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDisponibilidadeRoute =
  AuthenticatedAdminDisponibilidadeRouteImport.update({
    id: '/admin/disponibilidade',
    path: '/admin/disponibilidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSolicitacoesRoute =
  AuthenticatedAdminSolicitacoesRouteImport.update({
    id: '/admin/solicitacoes',
    path: '/admin/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesIndexRoute =
  AuthenticatedSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesNovaRoute =
  AuthenticatedSolicitacoesNovaRouteImport.update({
    id: '/solicitacoes/nova',
    path: '/solicitacoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMotoristasIndexRoute =
  AuthenticatedAdminMotoristasIndexRouteImport.update({
    id: '/admin/motoristas/',
    path: '/admin/motoristas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMotoristasDriverIdRoute =
  AuthenticatedAdminMotoristasDriverIdRouteImport.update({
    id: '/admin/motoristas/$driverId',
    path: '/admin/motoristas/$driverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsuariosRoute,
  } as any)
const AuthenticatedAdminUsuariosUserIdRoute =
  AuthenticatedAdminUsuariosUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsuariosRoute,
  } as any)
const AuthenticatedAdminVeiculosIndexRoute =
  AuthenticatedAdminVeiculosIndexRouteImport.update({
    id: '/admin/veiculos/',
    path: '/admin/veiculos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVeiculosVehicleIdRoute =
  AuthenticatedAdminVeiculosVehicleIdRouteImport.update({
    id: '/admin/veiculos/$vehicleId',
    path: '/admin/veiculos/$vehicleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesTripIdEditarRoute =
  AuthenticatedSolicitacoesTripIdEditarRouteImport.update({
    id: '/solicitacoes/$tripId/editar',
    path: '/solicitacoes/$tripId/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agenda-publica': typeof AuthenticatedAgendaPublicaRoute
  '/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/organizacao': typeof AuthenticatedOrganizacaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/setor': typeof AuthenticatedSetorRoute
  '/viagens': typeof AuthenticatedViagensRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/destinos': typeof AuthenticatedAdminDestinosRoute
  '/admin/disponibilidade': typeof AuthenticatedAdminDisponibilidadeRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
  '/admin/motoristas/$driverId': typeof AuthenticatedAdminMotoristasDriverIdRoute
  '/admin/usuarios/$userId': typeof AuthenticatedAdminUsuariosUserIdRoute
  '/admin/veiculos/$vehicleId': typeof AuthenticatedAdminVeiculosVehicleIdRoute
  '/solicitacoes/$tripId/editar': typeof AuthenticatedSolicitacoesTripIdEditarRoute
  '/admin/motoristas/': typeof AuthenticatedAdminMotoristasIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/admin/veiculos/': typeof AuthenticatedAdminVeiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agenda-publica': typeof AuthenticatedAgendaPublicaRoute
  '/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/organizacao': typeof AuthenticatedOrganizacaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/setor': typeof AuthenticatedSetorRoute
  '/viagens': typeof AuthenticatedViagensRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/admin/destinos': typeof AuthenticatedAdminDestinosRoute
  '/admin/disponibilidade': typeof AuthenticatedAdminDisponibilidadeRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesIndexRoute
  '/admin/motoristas/$driverId': typeof AuthenticatedAdminMotoristasDriverIdRoute
  '/admin/usuarios/$userId': typeof AuthenticatedAdminUsuariosUserIdRoute
  '/admin/veiculos/$vehicleId': typeof AuthenticatedAdminVeiculosVehicleIdRoute
  '/solicitacoes/$tripId/editar': typeof AuthenticatedSolicitacoesTripIdEditarRoute
  '/admin/motoristas': typeof AuthenticatedAdminMotoristasIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
  '/admin/veiculos': typeof AuthenticatedAdminVeiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/agenda-publica': typeof AuthenticatedAgendaPublicaRoute
  '/_authenticated/completar-cadastro': typeof AuthenticatedCompletarCadastroRoute
  '/_authenticated/organizacao': typeof AuthenticatedOrganizacaoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/setor': typeof AuthenticatedSetorRoute
  '/_authenticated/viagens': typeof AuthenticatedViagensRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/cidades': typeof AuthenticatedAdminCidadesRoute
  '/_authenticated/admin/destinos': typeof AuthenticatedAdminDestinosRoute
  '/_authenticated/admin/disponibilidade': typeof AuthenticatedAdminDisponibilidadeRoute
  '/_authenticated/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRouteWithChildren
  '/_authenticated/solicitacoes/nova': typeof AuthenticatedSolicitacoesNovaRoute
  '/_authenticated/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
  '/_authenticated/admin/motoristas/$driverId': typeof AuthenticatedAdminMotoristasDriverIdRoute
  '/_authenticated/admin/usuarios/$userId': typeof AuthenticatedAdminUsuariosUserIdRoute
  '/_authenticated/admin/veiculos/$vehicleId': typeof AuthenticatedAdminVeiculosVehicleIdRoute
  '/_authenticated/solicitacoes/$tripId/editar': typeof AuthenticatedSolicitacoesTripIdEditarRoute
  '/_authenticated/admin/motoristas/': typeof AuthenticatedAdminMotoristasIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
  '/_authenticated/admin/veiculos/': typeof AuthenticatedAdminVeiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda-publica'
    | '/completar-cadastro'
    | '/organizacao'
    | '/painel'
    | '/setor'
    | '/viagens'
    | '/auth/callback'
    | '/admin/cidades'
    | '/admin/destinos'
    | '/admin/disponibilidade'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/solicitacoes/nova'
    | '/solicitacoes/'
    | '/admin/motoristas/$driverId'
    | '/admin/usuarios/$userId'
    | '/admin/veiculos/$vehicleId'
    | '/solicitacoes/$tripId/editar'
    | '/admin/motoristas/'
    | '/admin/usuarios/'
    | '/admin/veiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda-publica'
    | '/completar-cadastro'
    | '/organizacao'
    | '/painel'
    | '/setor'
    | '/viagens'
    | '/auth/callback'
    | '/admin/cidades'
    | '/admin/destinos'
    | '/admin/disponibilidade'
    | '/admin/solicitacoes'
    | '/solicitacoes/nova'
    | '/solicitacoes'
    | '/admin/motoristas/$driverId'
    | '/admin/usuarios/$userId'
    | '/admin/veiculos/$vehicleId'
    | '/solicitacoes/$tripId/editar'
    | '/admin/motoristas'
    | '/admin/usuarios'
    | '/admin/veiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda-publica'
    | '/_authenticated/completar-cadastro'
    | '/_authenticated/organizacao'
    | '/_authenticated/painel'
    | '/_authenticated/setor'
    | '/_authenticated/viagens'
    | '/auth/callback'
    | '/_authenticated/admin/cidades'
    | '/_authenticated/admin/destinos'
    | '/_authenticated/admin/disponibilidade'
    | '/_authenticated/admin/solicitacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/solicitacoes/nova'
    | '/_authenticated/solicitacoes/'
    | '/_authenticated/admin/motoristas/$driverId'
    | '/_authenticated/admin/usuarios/$userId'
    | '/_authenticated/admin/veiculos/$vehicleId'
    | '/_authenticated/solicitacoes/$tripId/editar'
    | '/_authenticated/admin/motoristas/'
    | '/_authenticated/admin/usuarios/'
    | '/_authenticated/admin/veiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda-publica': {
      id: '/_authenticated/agenda-publica'
      path: '/agenda-publica'
      fullPath: '/agenda-publica'
      preLoaderRoute: typeof AuthenticatedAgendaPublicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/completar-cadastro': {
      id: '/_authenticated/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/completar-cadastro'
      preLoaderRoute: typeof AuthenticatedCompletarCadastroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizacao': {
      id: '/_authenticated/organizacao'
      path: '/organizacao'
      fullPath: '/organizacao'
      preLoaderRoute: typeof AuthenticatedOrganizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setor': {
      id: '/_authenticated/setor'
      path: '/setor'
      fullPath: '/setor'
      preLoaderRoute: typeof AuthenticatedSetorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viagens': {
      id: '/_authenticated/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof AuthenticatedViagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin/cidades': {
      id: '/_authenticated/admin/cidades'
      path: '/admin/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AuthenticatedAdminCidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/destinos': {
      id: '/_authenticated/admin/destinos'
      path: '/admin/destinos'
      fullPath: '/admin/destinos'
      preLoaderRoute: typeof AuthenticatedAdminDestinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/disponibilidade': {
      id: '/_authenticated/admin/disponibilidade'
      path: '/admin/disponibilidade'
      fullPath: '/admin/disponibilidade'
      preLoaderRoute: typeof AuthenticatedAdminDisponibilidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/solicitacoes': {
      id: '/_authenticated/admin/solicitacoes'
      path: '/admin/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/': {
      id: '/_authenticated/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/nova': {
      id: '/_authenticated/solicitacoes/nova'
      path: '/solicitacoes/nova'
      fullPath: '/solicitacoes/nova'
      preLoaderRoute: typeof AuthenticatedSolicitacoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/motoristas/': {
      id: '/_authenticated/admin/motoristas/'
      path: '/admin/motoristas'
      fullPath: '/admin/motoristas/'
      preLoaderRoute: typeof AuthenticatedAdminMotoristasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/motoristas/$driverId': {
      id: '/_authenticated/admin/motoristas/$driverId'
      path: '/admin/motoristas/$driverId'
      fullPath: '/admin/motoristas/$driverId'
      preLoaderRoute: typeof AuthenticatedAdminMotoristasDriverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsuariosRoute
    }
    '/_authenticated/admin/usuarios/$userId': {
      id: '/_authenticated/admin/usuarios/$userId'
      path: '/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsuariosRoute
    }
    '/_authenticated/admin/veiculos/': {
      id: '/_authenticated/admin/veiculos/'
      path: '/admin/veiculos'
      fullPath: '/admin/veiculos/'
      preLoaderRoute: typeof AuthenticatedAdminVeiculosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/veiculos/$vehicleId': {
      id: '/_authenticated/admin/veiculos/$vehicleId'
      path: '/admin/veiculos/$vehicleId'
      fullPath: '/admin/veiculos/$vehicleId'
      preLoaderRoute: typeof AuthenticatedAdminVeiculosVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/$tripId/editar': {
      id: '/_authenticated/solicitacoes/$tripId/editar'
      path: '/solicitacoes/$tripId/editar'
      fullPath: '/solicitacoes/$tripId/editar'
      preLoaderRoute: typeof AuthenticatedSolicitacoesTripIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminUsuariosRouteChildren {
  AuthenticatedAdminUsuariosUserIdRoute: typeof AuthenticatedAdminUsuariosUserIdRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
}

const AuthenticatedAdminUsuariosRouteChildren: AuthenticatedAdminUsuariosRouteChildren =
  {
    AuthenticatedAdminUsuariosUserIdRoute:
      AuthenticatedAdminUsuariosUserIdRoute,
    AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
  }

const AuthenticatedAdminUsuariosRouteWithChildren =
  AuthenticatedAdminUsuariosRoute._addFileChildren(
    AuthenticatedAdminUsuariosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaPublicaRoute: typeof AuthenticatedAgendaPublicaRoute
  AuthenticatedCompletarCadastroRoute: typeof AuthenticatedCompletarCadastroRoute
  AuthenticatedOrganizacaoRoute: typeof AuthenticatedOrganizacaoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedSetorRoute: typeof AuthenticatedSetorRoute
  AuthenticatedViagensRoute: typeof AuthenticatedViagensRoute
  AuthenticatedAdminCidadesRoute: typeof AuthenticatedAdminCidadesRoute
  AuthenticatedAdminDestinosRoute: typeof AuthenticatedAdminDestinosRoute
  AuthenticatedAdminDisponibilidadeRoute: typeof AuthenticatedAdminDisponibilidadeRoute
  AuthenticatedAdminSolicitacoesRoute: typeof AuthenticatedAdminSolicitacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRouteWithChildren
  AuthenticatedSolicitacoesNovaRoute: typeof AuthenticatedSolicitacoesNovaRoute
  AuthenticatedSolicitacoesIndexRoute: typeof AuthenticatedSolicitacoesIndexRoute
  AuthenticatedAdminMotoristasDriverIdRoute: typeof AuthenticatedAdminMotoristasDriverIdRoute
  AuthenticatedAdminVeiculosVehicleIdRoute: typeof AuthenticatedAdminVeiculosVehicleIdRoute
  AuthenticatedSolicitacoesTripIdEditarRoute: typeof AuthenticatedSolicitacoesTripIdEditarRoute
  AuthenticatedAdminMotoristasIndexRoute: typeof AuthenticatedAdminMotoristasIndexRoute
  AuthenticatedAdminVeiculosIndexRoute: typeof AuthenticatedAdminVeiculosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaPublicaRoute: AuthenticatedAgendaPublicaRoute,
  AuthenticatedCompletarCadastroRoute: AuthenticatedCompletarCadastroRoute,
  AuthenticatedOrganizacaoRoute: AuthenticatedOrganizacaoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedSetorRoute: AuthenticatedSetorRoute,
  AuthenticatedViagensRoute: AuthenticatedViagensRoute,
  AuthenticatedAdminCidadesRoute: AuthenticatedAdminCidadesRoute,
  AuthenticatedAdminDestinosRoute: AuthenticatedAdminDestinosRoute,
  AuthenticatedAdminDisponibilidadeRoute:
    AuthenticatedAdminDisponibilidadeRoute,
  AuthenticatedAdminSolicitacoesRoute: AuthenticatedAdminSolicitacoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRouteWithChildren,
  AuthenticatedSolicitacoesNovaRoute: AuthenticatedSolicitacoesNovaRoute,
  AuthenticatedSolicitacoesIndexRoute: AuthenticatedSolicitacoesIndexRoute,
  AuthenticatedAdminMotoristasDriverIdRoute:
    AuthenticatedAdminMotoristasDriverIdRoute,
  AuthenticatedAdminVeiculosVehicleIdRoute:
    AuthenticatedAdminVeiculosVehicleIdRoute,
  AuthenticatedSolicitacoesTripIdEditarRoute:
    AuthenticatedSolicitacoesTripIdEditarRoute,
  AuthenticatedAdminMotoristasIndexRoute:
    AuthenticatedAdminMotoristasIndexRoute,
  AuthenticatedAdminVeiculosIndexRoute: AuthenticatedAdminVeiculosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
