
-- ENUMS
DO $$ BEGIN
  CREATE TYPE public.schedule_status AS ENUM ('RASCUNHO','PLANEJADA','PUBLICADA','EM_EXECUCAO','CONCLUIDA','CANCELADA');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.assignment_status AS ENUM ('PENDENTE','PROGRAMADO','EM_ANDAMENTO','CONCLUIDO','NAO_REALIZADO','CANCELADO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.segment_type AS ENUM ('LEVAR','BUSCAR','DESLOCAMENTO','AGUARDAR','RETORNO');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- HELPERS
CREATE OR REPLACE FUNCTION public.is_sre_driver(_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = _user_id AND p.is_sre_driver AND p.is_active)
      OR EXISTS (SELECT 1 FROM public.drivers d WHERE d.profile_id = _user_id AND d.is_active);
$$;

-- TABELAS
CREATE TABLE public.daily_schedules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code integer GENERATED BY DEFAULT AS IDENTITY,
  schedule_date date NOT NULL,
  vehicle_id uuid REFERENCES public.vehicles(id) ON DELETE SET NULL,
  driver_id uuid REFERENCES public.drivers(id) ON DELETE SET NULL,
  driver_user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status public.schedule_status NOT NULL DEFAULT 'RASCUNHO',
  observations text,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX daily_schedules_date_idx ON public.daily_schedules (schedule_date);
CREATE INDEX daily_schedules_vehicle_idx ON public.daily_schedules (vehicle_id);
CREATE INDEX daily_schedules_driver_idx ON public.daily_schedules (driver_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_schedules TO authenticated;
GRANT ALL ON public.daily_schedules TO service_role;
ALTER TABLE public.daily_schedules ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.schedule_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id uuid NOT NULL REFERENCES public.daily_schedules(id) ON DELETE CASCADE,
  trip_id uuid REFERENCES public.trip_requests(id) ON DELETE SET NULL,
  order_index integer NOT NULL DEFAULT 1,
  segment_type public.segment_type NOT NULL DEFAULT 'LEVAR',
  origin_city_id uuid REFERENCES public.cities(id) ON DELETE SET NULL,
  origin_destination_id uuid REFERENCES public.destinations(id) ON DELETE SET NULL,
  origin_text text NOT NULL DEFAULT 'SRE',
  destination_city_id uuid REFERENCES public.cities(id) ON DELETE SET NULL,
  destination_id uuid REFERENCES public.destinations(id) ON DELETE SET NULL,
  destination_text text NOT NULL DEFAULT '',
  requested_at timestamptz,
  scheduled_departure timestamptz NOT NULL,
  scheduled_arrival timestamptz NOT NULL,
  actual_departure timestamptz,
  actual_arrival timestamptz,
  passengers integer NOT NULL DEFAULT 0,
  passengers_names text,
  status public.assignment_status NOT NULL DEFAULT 'PROGRAMADO',
  notes text,
  created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT schedule_assignments_period_check CHECK (scheduled_arrival > scheduled_departure)
);
CREATE INDEX schedule_assignments_schedule_idx ON public.schedule_assignments (schedule_id, order_index);
CREATE INDEX schedule_assignments_trip_idx ON public.schedule_assignments (trip_id);
CREATE INDEX schedule_assignments_dep_idx ON public.schedule_assignments (scheduled_departure);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.schedule_assignments TO authenticated;
GRANT ALL ON public.schedule_assignments TO service_role;
ALTER TABLE public.schedule_assignments ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.schedule_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id uuid NOT NULL REFERENCES public.daily_schedules(id) ON DELETE CASCADE,
  assignment_id uuid REFERENCES public.schedule_assignments(id) ON DELETE SET NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  field_changed text,
  old_value text,
  new_value text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX schedule_history_schedule_idx ON public.schedule_history (schedule_id, created_at DESC);

GRANT SELECT, INSERT ON public.schedule_history TO authenticated;
GRANT ALL ON public.schedule_history TO service_role;
ALTER TABLE public.schedule_history ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.schedule_incidents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id uuid NOT NULL REFERENCES public.daily_schedules(id) ON DELETE CASCADE,
  assignment_id uuid REFERENCES public.schedule_assignments(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  kind text NOT NULL DEFAULT 'OUTRO',
  description text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX schedule_incidents_schedule_idx ON public.schedule_incidents (schedule_id, created_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.schedule_incidents TO authenticated;
GRANT ALL ON public.schedule_incidents TO service_role;
ALTER TABLE public.schedule_incidents ENABLE ROW LEVEL SECURITY;

-- É o motorista responsável pela escala?
CREATE OR REPLACE FUNCTION public.is_schedule_driver(_schedule_id uuid, _user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.daily_schedules s
    LEFT JOIN public.drivers d ON d.id = s.driver_id
    WHERE s.id = _schedule_id
      AND (s.driver_user_id = _user_id OR d.profile_id = _user_id OR s.created_by = _user_id)
  );
$$;

-- POLICIES
CREATE POLICY "escalas visiveis" ON public.daily_schedules
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin gerencia escalas" ON public.daily_schedules
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "motorista cria escala" ON public.daily_schedules
  FOR INSERT TO authenticated
  WITH CHECK (is_sre_driver(auth.uid()) AND created_by = auth.uid());
CREATE POLICY "motorista edita propria escala" ON public.daily_schedules
  FOR UPDATE TO authenticated
  USING (is_sre_driver(auth.uid()) AND is_schedule_driver(id, auth.uid()))
  WITH CHECK (is_sre_driver(auth.uid()) AND is_schedule_driver(id, auth.uid()));

CREATE POLICY "atendimentos visiveis" ON public.schedule_assignments
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin gerencia atendimentos" ON public.schedule_assignments
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "motorista gerencia atendimentos da sua escala" ON public.schedule_assignments
  FOR ALL TO authenticated
  USING (is_sre_driver(auth.uid()) AND is_schedule_driver(schedule_id, auth.uid()))
  WITH CHECK (is_sre_driver(auth.uid()) AND is_schedule_driver(schedule_id, auth.uid()));

CREATE POLICY "historico da escala visivel" ON public.schedule_history
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "registra historico da escala" ON public.schedule_history
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "ocorrencias visiveis" ON public.schedule_incidents
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin gerencia ocorrencias" ON public.schedule_incidents
  FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "motorista registra ocorrencia" ON public.schedule_incidents
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND is_sre_driver(auth.uid()));

-- updated_at
CREATE TRIGGER daily_schedules_updated_at BEFORE UPDATE ON public.daily_schedules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER schedule_assignments_updated_at BEFORE UPDATE ON public.schedule_assignments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Uma viagem não pode estar em duas escalas ativas
CREATE OR REPLACE FUNCTION public.check_trip_single_schedule()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.trip_id IS NULL OR NEW.status = 'CANCELADO' THEN
    RETURN NEW;
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.schedule_assignments a
    JOIN public.daily_schedules s ON s.id = a.schedule_id
    WHERE a.trip_id = NEW.trip_id
      AND a.id <> NEW.id
      AND a.schedule_id <> NEW.schedule_id
      AND a.status <> 'CANCELADO'
      AND s.status <> 'CANCELADA'
  ) THEN
    RAISE EXCEPTION 'Esta solicitação já faz parte de outra escala ativa.';
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER schedule_assignments_single_schedule
  BEFORE INSERT OR UPDATE ON public.schedule_assignments
  FOR EACH ROW EXECUTE FUNCTION public.check_trip_single_schedule();

-- Conflitos de veículo e motorista em um intervalo
CREATE OR REPLACE FUNCTION public.schedule_conflicts(
  _vehicle_id uuid,
  _driver_id uuid,
  _driver_user_id uuid,
  _start timestamptz,
  _end timestamptz,
  _exclude_assignment uuid DEFAULT NULL
)
RETURNS TABLE (
  kind text,
  assignment_id uuid,
  schedule_id uuid,
  schedule_code integer,
  label text,
  starts_at timestamptz,
  ends_at timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT
    CASE
      WHEN _vehicle_id IS NOT NULL AND s.vehicle_id = _vehicle_id THEN 'VEICULO'
      ELSE 'MOTORISTA'
    END AS kind,
    a.id, s.id, s.code,
    COALESCE(NULLIF(a.origin_text,''),'—') || ' → ' || COALESCE(NULLIF(a.destination_text,''),'—'),
    a.scheduled_departure, a.scheduled_arrival
  FROM public.schedule_assignments a
  JOIN public.daily_schedules s ON s.id = a.schedule_id
  WHERE a.status <> 'CANCELADO'
    AND s.status <> 'CANCELADA'
    AND (_exclude_assignment IS NULL OR a.id <> _exclude_assignment)
    AND tstzrange(a.scheduled_departure, a.scheduled_arrival, '[)')
        && tstzrange(_start, _end, '[)')
    AND (
      (_vehicle_id IS NOT NULL AND s.vehicle_id = _vehicle_id)
      OR (_driver_id IS NOT NULL AND s.driver_id = _driver_id)
      OR (_driver_user_id IS NOT NULL AND s.driver_user_id = _driver_user_id)
    )
  ORDER BY a.scheduled_departure;
$$;

-- Próximo horário livre a partir de um instante, mantendo a duração
CREATE OR REPLACE FUNCTION public.suggest_free_slot(
  _vehicle_id uuid,
  _driver_id uuid,
  _driver_user_id uuid,
  _start timestamptz,
  _end timestamptz,
  _exclude_assignment uuid DEFAULT NULL
)
RETURNS timestamptz
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  dur interval := _end - _start;
  cursor_at timestamptz := _start;
  conflict_end timestamptz;
  guard integer := 0;
BEGIN
  LOOP
    guard := guard + 1;
    EXIT WHEN guard > 50;
    SELECT max(c.ends_at) INTO conflict_end
    FROM public.schedule_conflicts(_vehicle_id, _driver_id, _driver_user_id, cursor_at, cursor_at + dur, _exclude_assignment) c;
    IF conflict_end IS NULL THEN
      RETURN cursor_at;
    END IF;
    cursor_at := conflict_end;
  END LOOP;
  RETURN cursor_at;
END $$;

-- Notificação pelo sino existente (admin e motoristas da SRE)
CREATE OR REPLACE FUNCTION public.notify_users(
  _user_ids uuid[],
  _title text,
  _body text,
  _trip_id uuid DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  inserted integer := 0;
BEGIN
  IF NOT (is_admin() OR is_sre_driver(auth.uid())) THEN
    RAISE EXCEPTION 'Sem permissão para notificar usuários.';
  END IF;
  INSERT INTO public.notifications (user_id, title, body, trip_id)
  SELECT DISTINCT u, _title, _body, _trip_id
  FROM unnest(_user_ids) AS u
  WHERE u IS NOT NULL;
  GET DIAGNOSTICS inserted = ROW_COUNT;
  RETURN inserted;
END $$;

GRANT EXECUTE ON FUNCTION public.schedule_conflicts(uuid,uuid,uuid,timestamptz,timestamptz,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.suggest_free_slot(uuid,uuid,uuid,timestamptz,timestamptz,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.notify_users(uuid[],text,text,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_sre_driver(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_schedule_driver(uuid,uuid) TO authenticated;
